### ISSUE TITLE
still crashes

### ISSUE THREAD

**Issue by christomite** [Darkhax-Minecraft/Bookshelf#138]
still crashes with flux networks removed new crash
[crash-2020-05-15_19.42.31-client.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/4637590/crash-2020-05-15_19.42.31-client.txt)

**Comment by SonarSonic** [comment]
This isn't caused by bookshelf or Flux Networks.
Due to the parallel loading forge added, it causes crashes during the loading phase to be ignored, you'll need to look at your debug.log and you should be able to find the mod causing it.

Forge Issue:
MinecraftForge/MinecraftForge#6374

Duplicates:
Darkhax-Minecraft/Bookshelf#137 & SonarSonic/Flux-Networks#374
