### ISSUE TITLE
maven.mcmoddev.com no longer resolves dns

### ISSUE THREAD

**Issue by dtorgy** [Darkhax-Minecraft/Bookshelf#155]
I am sorry if this is posted in the wrong project, I was not sure where to post it.

I am unable to resolve maven.mcmoddev.com. It appears that the name servers listed on the domain (NS1.CYBERKAT.EU - NS5.CYBERKAT.EU) no longer are answering DNS queries.

**Comment by Darkhax** [comment]
Hello, this is a known issue. The cyberkat.eu name server was suspended on the 1st because Brexit finally went through and the domain was registered to a UK address. I don't control either domain and expect there to be some serious down time for both. 

For now you can use `https://mmdmaven.blamejared.com/` to access the same server.
