### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NotBadli** [Darkhax-Minecraft/Bookshelf#185]
I'm getting this error. Tried even removing, still appeared.
`[13:40:16] [Render thread/ERROR]: Couldn't load tag bookshelf:strings as it is missing following references: #c:strings (from Bookshelf), #c:string (from Bookshelf)`
Log: [latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/8878835/latest.log)

**Comment by Darkhax** [comment]
This issue happens when required datapack elements are disabled, in this case the comming string tag. Based on your log file this was disabled intentionally disabled or a bug with another mod. 

> [15:03:22] [Render thread/INFO]: Skipping Data Pack. Disabled by user config.

> [15:28:16] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/resource/loader/FabricResource
