### ISSUE TITLE
Duplicate Potion ID, crashes while loading.

### ISSUE THREAD

**Issue by DinckelMan** [Darkhax-Minecraft/Bookshelf#20]
[Crash log](https://github.com/Darkhax-Minecraft/Bookshelf/files/58848/crash-2015-12-11_00.04.05-client.txt)

**Comment by iLexiconn** [comment]
This really isn't a bug, but a feature. I know it sounds like a lame excuse, but whatever. Bookshelf detects the potion IDs and reports it, so you can report it to the mod authors.
In this case mods `alchemicalWizardry` and `shadowfox_botany` are the errored mods. You should report it there, and they can fix it.

**Comment by darkhax** [comment]
As iLexiconn said, this is part of a feature within Bookshelf. Only a certain amount of potions can be added to the game, and each one needs a number ID to go with it. With Bookshelf installed, the numbers can range from 0 to 255. Since this is such a small range, it is not uncommon for mods with potions to use the same ID. While you can normally start the game with two potions using the same ID, this leads itself to a wide range of glitches, crashes and general stability issues. 

In this specific case, the Potion of Planar Binding from Alchemical Wizardry and the Potion of Mana Void from Shadowfox_botant are using the ID of 110. Most mods which add a potion will also add an option in their configuration file to change the id from the default to a new value. By changing one of them from 110 to another unused value, will solve this issue. Given how common it is more mods to have conflicting potion ID values, I wouldn't be surprised if you will have to change multiple potion ids. Because this is not an issue with those mods, and the best they can tell you is to change it in the config file yourself, I would advise not reporting it to the mod authors. 

Although this issue is being closed, it is not locked. If you have any questions or need help, feel free to ask.
