### ISSUE TITLE
Support for MC 1.20.2

### ISSUE THREAD

**Issue by QarthO** [Darkhax-Minecraft/Bookshelf#220]
Allow support for 1.20.2. Simple as that

**Comment by wolvyreen** [comment]
I see there was a new update for 1.20.1 but not for 1.20.2. Any news on an update for 1.20.2?

**Comment by wolvyreen** [comment]
I see the update for 1.20.2 was released yesterday.  YAY!  Thanks DarkhaxDev

**Comment by Darkhax** [comment]
Hey, as you've noticed an update for 1.20.2 is up. You can find all current and future 1.20.2 updates [here](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files?page=1&pageSize=20&version=1.20.2).

I've shared a bit about this update on Discord but I wouldn't blame anyone for not keeping up with that. The TLDR is that Forge has been very unstable since 48.0.0 and NeoForge has not updated yet so I put things on hold while waiting for things to settle down. Unfortunately I can't wait around forever though so I've just released what I can.
