### ISSUE TITLE
[Bug] Possible crash pertaining to Bookshelf

### ISSUE THREAD

**Issue by dylanjkl** [Darkhax-Minecraft/Bookshelf#224]
Crash occurs whenever a player receives the poison status effect. 
There is references to bookshelf early in the stack-trace however I am unsure if it's directly correlated. 

**xf:fml:forge:potion,pl:mixin:APP:bookshelf.common.mixins.json:accessors.effect.AccessorMobEffectInstance from mod bookshelf**

Posting here just in-case.

[crash-2024-01-28-client.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/14074732/crash-2024-01-28-client.txt)

**Comment by Darkhax** [comment]
Hello, unfortunately this is not related to Bookshelf. The mixin referenced there is an accessor that is only being used in a read-only context. This crash is because the game is trying to damage the player with `forge:poison` damage, but the correct ID is `minecraft:poison`. The log file has no indication of what mod is using the wrong ID here.
