### ISSUE TITLE
[QUESTION] <Do I need to download the specified version for different mod loader or are all versions the same on cursed forge?>

### ISSUE THREAD

**Issue by RakibRyan** [Darkhax-Minecraft/Bookshelf#230]
### Question

new to minecraft so still figuring out

**Comment by Darkhax** [comment]
Hello, you almost always want to download the mod file that has the same Minecraft version and mod loader as you. For example if you're playing Minecraft Forge 1.16.5 with Forge you can not use Fabric files or a file from Minecraft 1.14 or 1.19.2. This is because Minecraft changes their code in a way that breaks mods in every update, even minor patches. Each mod loader also has different code and are usually not intercompatible.

There are some exceptions but I personally don't think much about them and try to clearly label all my files on CurseForge to make things simpler for players. 

- On 1.20.1 Forge files can usually be used with NeoForge
- Fabric mods can usually be used on Quilt but Quilt mods can not be used on Fabric.
