### ISSUE TITLE
Crash without network access

### ISSUE THREAD

**Issue by Thiana** [Darkhax-Minecraft/Bookshelf#38]
Bookshelf is crashing with a SocketException when it can't access the network. Crash log is http://pastebin.com/2DV6FuVW.

Versions:
MC 1.9.4
Forge 1964
Bookshelf 1.2.3.268

Thanks.

**Comment by darkhax** [comment]
I believe there may be something more going on here. The error message from Bookshelf is intended, it lets anyone reading the crash know that you could not connect to the internet, and any related features should not work. It does not point to a crash with the Bookshelf mod. 

The real issue seems to be from the BTFU mod. Something to do with a backup configuration directory not being set. Try running the game without BTFU.

**Comment by Thiana** [comment]
*sigh* The one time I decide to skip isolation testing for the error. You're correct, it was the backup mod. Thanks :)
