### ISSUE TITLE
Bookshelf causes incompatibilities with Thermal Expansion

### ISSUE THREAD

**Issue by 2ndkirbyever** [Darkhax-Minecraft/Bookshelf#80]
I reported this on the CoFH repo earlier tonight, but after four minutes, KingLemming let me know that Bookshelf is causing items to not be displayed in JEI and causing a crash when trying to look up a recipe with a hidden item: https://github.com/CoFH/Feedback/issues/350

**Comment by KingLemming** [comment]
Basically what seems to be happening here is that the wrapper is incompatible with CCRenderItem, and it's wrapping it for whatever reason.

What exactly are you wrapping and why?

**Comment by darkhax** [comment]
The wrapper in question is the same as the wrapper in CodeChickenLib. It's been removed for a very long time now because I stopped using it in favour of merging multiple baked models together. This was a change in 1.11.2 though. My wrapper doesn't actually change any of the data, and just passes the call on to the parent wrapper unless it's one of the special blocks. For example, I have a tank mod which used this for rendering fluids, before Forge had worked out their own fluid model system. You can find the code for that old system [here](https://github.com/Darkhax-Minecraft/Bookshelf/tree/1.10.2/src/main/java/net/darkhax/bookshelf/client/render/item)

**Comment by 2ndkirbyever** [comment]
Thanks for all of your help. CodeChickenLib released an update today whose changelog states "Gracefully catch mod bakeries exploding." The items that were hidden in JEI are visible again, and the game is functioning normally.
